[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[environments.production]
variables = { CI_ENV = "production", APP_DEBUG = "false" }
